### ISSUE TITLE
Illegal value for Message.Field .lnrpc.Invoice.value of type int64

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-lnd-asym-client#6]
ilp-plugin-lightning:server RPC Error: Illegal value for Message.Field .lnrpc.Invoice.value of type int64: object (no array expected). Message was {"type":"Buffer","data":[6,210,242,171,75,32,1,1,22,95,103,101,116,95,108,105,103,104,116,110,105,110,103,95,105,110,118,111,105,99,101,2,5,91,34,49,34,93]} +3ms

**Comment by michielbdejong** [comment]
This seems to refer to https://github.com/interledgerjs/ilp-plugin-lightning/blob/master/src/rpc.proto#L1152

**Comment by michielbdejong** [comment]
It seems grpc is ok with receiving strings that represent Int64, but maybe there's a problem with map (object) vs. array of arrays. This stack trace will probably help debug that:
```sh

  ilp-plugin-lightning creating lightning invoice for amount [ '1' ] +0ms
addInvoice call [ '1' ]
  ilp-plugin-lightning:server Error calling message handler TYPE_MESSAGE:  Error: Illegal value for Message.Field .lnrpc.Invoice.value of type int64: object (no array expected)
    at fail (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/protobufjs/dist/protobuf.js:3465:23)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/protobufjs/dist/protobuf.js:3497:17)
    at MessagePrototype.set (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/protobufjs/dist/protobuf.js:2493:59)
    at MessagePrototype.set (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/protobufjs/dist/protobuf.js:2483:38)
    at Message (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/protobufjs/dist/protobuf.js:2411:34)
    at serialize (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/grpc/src/protobuf_js_5_common.js:66:23)
    at ServiceClient.Client.makeUnaryRequest (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/grpc/src/client.js:515:17)
    at apply (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/lodash/lodash.js:499:17)
    at ServiceClient.wrapper (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/node_modules/lodash/lodash.js:5356:16)
    at Promise (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/src/plugin.js:221:15) +1ms

**Comment by michielbdejong** [comment]
Fixed in the December sprint branch
