### ISSUE TITLE
Cannot decode payment requests

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-lnd-asym-client#7]
The sender checks whether the invoice from the receiver has the right amount, but for that, it needs to zbase32-decode the `pay_req`. That process is currently failing with:
```sh
Error: String is corrupted at 0
    at Object.decodeString (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/src/zbase32.js:44:15)
    at decodePaymentRequest (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/src/reqdecode.js:25:27)
    at payLightningInvoice (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/src/plugin.js:185:22)
    at Object.createOutgoingClaim (/Users/michiel/gh/interledgerjs/ilp-plugin-lightning/src/plugin.js:161:35)
    at process._tickCallback (internal/process/next_tick.js:109:7) +0ms

**Comment by michielbdejong** [comment]
Fixed in #4
